<?xml version="1.0" encoding="UTF-8"?>

<testsuite tests="5" name="junit.framework.TestSuite" failures="5" errors="0" time="19.236" hostename="macintosh-2.local" timestamp="2018-11-16T15:13:18">
  <testcase time="3.514" classname="junit.framework.TestSuite" name="apitest: 
sample api testcase">
    <failure message="/Users/henrywasserman/test/bitbucket/apitesttool/data/consult//response/apitest_0.xml ***/Users/henrywasserman/test/bitbucket/apitesttool/data/consult//response/apitest_0.xml
[different] Expected text value 'female' but was 'male' - comparing &lt;gender ...&gt;female&lt;/gender&gt; at /root[1]/results[1]/results[1]/gender[1]/text()[1] to &lt;gender ...&gt;male&lt;/gender&gt; at /root[1]/results[1]/results[1]/gender[1]/text()[1]

[different] Expected text value 'ms' but was 'mr' - comparing &lt;title ...&gt;ms&lt;/title&gt; at /root[1]/results[1]/results[1]/name[1]/title[1]/text()[1] to &lt;title ...&gt;mr&lt;/title&gt; at /root[1]/results[1]...error messages truncated" type="java.lang.AssertionError">java.lang.AssertionError: /Users/henrywasserman/test/bitbucket/apitesttool/data/consult//response/apitest_0.xml ***/Users/henrywasserman/test/bitbucket/apitesttool/data/consult//response/apitest_0.xml
[different] Expected text value 'female' but was 'male' - comparing &lt;gender ...&gt;female&lt;/gender&gt; at /root[1]/results[1]/results[1]/gender[1]/text()[1] to &lt;gender ...&gt;male&lt;/gender&gt; at /root[1]/results[1]/results[1]/gender[1]/text()[1]

[different] Expected text value 'ms' but was 'mr' - comparing &lt;title ...&gt;ms&lt;/title&gt; at /root[1]/results[1]/results[1]/name[1]/title[1]/text()[1] to &lt;title ...&gt;mr&lt;/title&gt; at /root[1]/results[1]...error messages truncated
	at org.junit.Assert.fail(Assert.java:88)
	at com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:148)
	at com.pqi.responsecompare.request.MakeRequestTest.main(MakeRequestTest.java:55)
</failure>  </testcase>  <testcase time="0.352" classname="junit.framework.TestSuite" name="test1: 
test description">    <failure message="/Users/henrywasserman/test/bitbucket/apitesttool/data/consult//response/test1_0.xml***TestID: test1 failed: 
 File 'data/consult/datadriven/sqlfarm.sql' does not exist
 org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)org.apache.commons.io.FileUtils.readLines(FileUtils.java:1783)org.apache.commons.io.FileUtils.readLines(FileUtils.java:1819)com.pqi.responsecompare.request.RunSQLFromFile.sendRequest(RunSQLFromFile.java:50)com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:159)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)junit.framework.TestCase.runTest(TestCase.java:176)junit.framework.TestCase.runBare(TestCase.java:141)junit.framework.TestResult$1.protect(TestResult.java:122)junit.framework.TestResult.runProtected(TestResult.java:142)junit.framework.TestResult.run(TestResult.java:125)junit.framework.TestCase.run(TestCase.java:129)junit.framework.TestSuite.runTest(TestSuite.java:255)junit.framework.TestSuite.r" type="java.lang.AssertionError">java.lang.AssertionError: /Users/henrywasserman/test/bitbucket/apitesttool/data/consult//response/test1_0.xml***TestID: test1 failed: 
 File 'data/consult/datadriven/sqlfarm.sql' does not exist
 org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)org.apache.commons.io.FileUtils.readLines(FileUtils.java:1783)org.apache.commons.io.FileUtils.readLines(FileUtils.java:1819)com.pqi.responsecompare.request.RunSQLFromFile.sendRequest(RunSQLFromFile.java:50)com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:159)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)junit.framework.TestCase.runTest(TestCase.java:176)junit.framework.TestCase.runBare(TestCase.java:141)junit.framework.TestResult$1.protect(TestResult.java:122)junit.framework.TestResult.runProtected(TestResult.java:142)junit.framework.TestResult.run(TestResult.java:125)junit.framework.TestCase.run(TestCase.java:129)junit.framework.TestSuite.runTest(TestSuite.java:255)junit.framework.TestSuite.r
	at org.junit.Assert.fail(Assert.java:88)
	at com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:148)
	at com.pqi.responsecompare.request.MakeRequestTest.main(MakeRequestTest.java:55)
</failure>  </testcase>  <testcase time="0.004" classname="junit.framework.TestSuite" name="FirstSQLTestcase: 
This is the First Sql Testcase">    <failure message="/Users/henrywasserman/test/bitbucket/apitesttool/data/consult//response/FirstSQLTestcase_0.xml***TestID: FirstSQLTestcase failed: 
 null
 com.pqi.responsecompare.sql.DatabaseManager.executeQuery(DatabaseManager.java:78)com.pqi.responsecompare.request.RunOracleSQL.executeAndValidateSql(RunOracleSQL.java:56)com.pqi.responsecompare.request.RunOracleSQL.sendRequest(RunOracleSQL.java:37)com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:159)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)junit.framework.TestCase.runTest(TestCase.java:176)junit.framework.TestCase.runBare(TestCase.java:141)junit.framework.TestResult$1.protect(TestResult.java:122)junit.framework.TestResult.runProtected(TestResult.java:142)junit.framework.TestResult.run(TestResult.java:125)junit.framework.TestCase.run(TestCase.java:129)junit.framework.TestSuite.runTest(TestSuite.java:255)junit.framework.TestSuite.run(TestSuite.java:250)org." type="java.lang.AssertionError">java.lang.AssertionError: /Users/henrywasserman/test/bitbucket/apitesttool/data/consult//response/FirstSQLTestcase_0.xml***TestID: FirstSQLTestcase failed: 
 null
 com.pqi.responsecompare.sql.DatabaseManager.executeQuery(DatabaseManager.java:78)com.pqi.responsecompare.request.RunOracleSQL.executeAndValidateSql(RunOracleSQL.java:56)com.pqi.responsecompare.request.RunOracleSQL.sendRequest(RunOracleSQL.java:37)com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:159)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)junit.framework.TestCase.runTest(TestCase.java:176)junit.framework.TestCase.runBare(TestCase.java:141)junit.framework.TestResult$1.protect(TestResult.java:122)junit.framework.TestResult.runProtected(TestResult.java:142)junit.framework.TestResult.run(TestResult.java:125)junit.framework.TestCase.run(TestCase.java:129)junit.framework.TestSuite.runTest(TestSuite.java:255)junit.framework.TestSuite.run(TestSuite.java:250)org.
	at org.junit.Assert.fail(Assert.java:88)
	at com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:148)
	at com.pqi.responsecompare.request.MakeRequestTest.main(MakeRequestTest.java:55)
</failure>  </testcase>  <testcase time="14.697" classname="junit.framework.TestSuite" name="Patrick1: 
first real world testcase">    <failure message="/Users/henrywasserman/test/bitbucket/apitesttool/data/consult//response/Patrick1_0.xml ***Could not obtain database connection The connection to the host Srvmlbsqlt05, named instance cca failed. Error: &quot;java.net.UnknownHostException: Srvmlbsqlt05&quot;. Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host." type="java.lang.AssertionError">java.lang.AssertionError: /Users/henrywasserman/test/bitbucket/apitesttool/data/consult//response/Patrick1_0.xml ***Could not obtain database connection The connection to the host Srvmlbsqlt05, named instance cca failed. Error: "java.net.UnknownHostException: Srvmlbsqlt05". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.
	at org.junit.Assert.fail(Assert.java:88)
	at com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:148)
	at com.pqi.responsecompare.request.MakeRequestTest.main(MakeRequestTest.java:55)
</failure>  </testcase>  <testcase time="0.666" classname="junit.framework.TestSuite" name="sqltest: 
sample sql testcase">    <failure message="/Users/henrywasserman/test/bitbucket/apitesttool/data/consult//response/sqltest_1.xml ***address[]
Expected: 84477 henry gateway
     but none found
 ; address[]
Unexpected: 84478 henry gateway
" type="java.lang.AssertionError">java.lang.AssertionError: /Users/henrywasserman/test/bitbucket/apitesttool/data/consult//response/sqltest_1.xml ***address[]
Expected: 84477 henry gateway
     but none found
 ; address[]
Unexpected: 84478 henry gateway

	at org.junit.Assert.fail(Assert.java:88)
	at com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:148)
	at com.pqi.responsecompare.request.MakeRequestTest.main(MakeRequestTest.java:55)
</failure>  </testcase>  <system-out><![CDATA[]]></system-out>  <system-err><![CDATA[SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:743)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:666)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:566)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.pqi.responsecompare.sql.OracleDbManager.getConnection(OracleDbManager.java:44)
	at com.pqi.responsecompare.sql.DatabaseManager.<init>(DatabaseManager.java:40)
	at com.pqi.responsecompare.sql.OracleDbManager.<init>(OracleDbManager.java:16)
	at com.pqi.responsecompare.request.RunSQLFromFile.sendRequest(RunSQLFromFile.java:43)
	at com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:148)
	at com.pqi.responsecompare.request.MakeRequestTest.main(MakeRequestTest.java:55)
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:470)
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:506)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:595)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:230)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1452)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:496)
	... 26 more
Caused by: java.net.UnknownHostException: srvmedmpbet01: nodename nor servname provided, or not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:120)
	at oracle.net.nt.ConnOption.connect(ConnOption.java:159)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:428)
	... 31 more
java.io.FileNotFoundException: File 'data/consult/datadriven/sqlfarm.sql' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.readLines(FileUtils.java:1783)
	at org.apache.commons.io.FileUtils.readLines(FileUtils.java:1819)
	at com.pqi.responsecompare.request.RunSQLFromFile.sendRequest(RunSQLFromFile.java:50)
	at com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:148)
	at com.pqi.responsecompare.request.MakeRequestTest.main(MakeRequestTest.java:55)
java.io.FileNotFoundException: File 'data/consult/datadriven/sqlfarm.sql' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.readLines(FileUtils.java:1783)
	at org.apache.commons.io.FileUtils.readLines(FileUtils.java:1819)
	at com.pqi.responsecompare.request.RunSQLFromFile.sendRequest(RunSQLFromFile.java:50)
	at com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:148)
	at com.pqi.responsecompare.request.MakeRequestTest.main(MakeRequestTest.java:55)
java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:743)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:666)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:566)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.pqi.responsecompare.sql.OracleDbManager.getConnection(OracleDbManager.java:44)
	at com.pqi.responsecompare.sql.DatabaseManager.<init>(DatabaseManager.java:40)
	at com.pqi.responsecompare.sql.OracleDbManager.<init>(OracleDbManager.java:16)
	at com.pqi.responsecompare.request.RunOracleSQL.sendRequest(RunOracleSQL.java:29)
	at com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:148)
	at com.pqi.responsecompare.request.MakeRequestTest.main(MakeRequestTest.java:55)
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:470)
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:506)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:595)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:230)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1452)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:496)
	... 26 more
Caused by: java.net.UnknownHostException: srvmedmpbet01
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:120)
	at oracle.net.nt.ConnOption.connect(ConnOption.java:159)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:428)
	... 31 more
java.lang.NullPointerException
	at com.pqi.responsecompare.sql.DatabaseManager.executeQuery(DatabaseManager.java:78)
	at com.pqi.responsecompare.request.RunOracleSQL.executeAndValidateSql(RunOracleSQL.java:56)
	at com.pqi.responsecompare.request.RunOracleSQL.sendRequest(RunOracleSQL.java:37)
	at com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:148)
	at com.pqi.responsecompare.request.MakeRequestTest.main(MakeRequestTest.java:55)
java.lang.NullPointerException
	at com.pqi.responsecompare.sql.DatabaseManager.executeQuery(DatabaseManager.java:78)
	at com.pqi.responsecompare.request.RunOracleSQL.executeAndValidateSql(RunOracleSQL.java:56)
	at com.pqi.responsecompare.request.RunOracleSQL.sendRequest(RunOracleSQL.java:37)
	at com.pqi.responsecompare.request.MakeRequestTest.MakeRequest(MakeRequestTest.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:148)
	at com.pqi.responsecompare.request.MakeRequestTest.main(MakeRequestTest.java:55)
]]></system-err></testsuite>